#!/usr/bin/env bash
set -e

clean=0
input_dir="."
output_dir=""

print_usage() {
  echo "Usage: $(basename "$0") [option]..."
  echo "Options:"
  echo "  -c    Remove po files after compile"
  echo "  -i    Input dir"
  echo "  -o    Output dir"
}

while getopts ':ci:o:' OPTION; do
  case "${OPTION}" in
  c)
    clean=1
    ;;
  i)
    input_dir="${OPTARG}"
    ;;
  o)
    output_dir="${OPTARG}"
    ;;
  ?)
    print_usage
    exit 1
    ;;
  esac
done

if [ -z "${output_dir}" ]; then
  output_dir=$(realpath "${input_dir}")
fi

cd "${input_dir}"
for po in *.po; do
  po2lmo "${po}" "${output_dir}/$(basename -s .po "${po}").lmo"
  [ "${clean}" = 1 ] && rm "${po}"
done
